### ISSUE TITLE
If services from two different pipelines have the same name, they share the same HTML ID

### ISSUE THREAD

**Issue by asjongers** [big-data-europe/ember-swarm-ui-engine#1]
Possible fix would be to incorporate the index in the id.

**Comment by fr0gs** [comment]
I don't see any crash, is that a problem?

**Comment by lordblendi** [comment]
The moment you want to filter on two HTML IDs, there will be a problem so we should avoid it. Suggested solution is to add a `dasherized-pipeline-name-` prefix, as the pipeline name with the time stamp should be unique.

**Comment by fr0gs** [comment]
@asjongers @lordblendi  I already fixed this in conjunction with https://github.com/big-data-europe/ember-swarm-ui-engine/issues/2
