### ISSUE TITLE
Loading screen on adding stack

### ISSUE THREAD

**Issue by lordblendi** [big-data-europe/ember-swarm-ui-engine#4]
When adding a new stack, we should block the actions until the docker-compose file is added. Otherwise if there is no docker-compose file added, clicking on 'launch pipeline' or 'edit docker compose file'  breaks the frontend.

**Comment by fr0gs** [comment]
Solved in https://github.com/big-data-europe/ember-swarm-ui-engine/commit/076621f3a4a5b66971dbe3c89e9a2a86494b87bb

Sorry I forgot to add the issue number, I will remember next time.
